/group1/ctrl:
  ros__parameters:
    ctrl_gain_P: 1.3
    ctrl_gain_I: 0.4
    ctrl_gain_D: 0.6

/group2/ctrl:
  ros__parameters:
    ctrl_gain_P: 1.8
    ctrl_gain_I: 0.9
    ctrl_gain_D: 1.1

/group3/ctrl:
  ros__parameters:
    ctrl_gain_P: 1.6
    ctrl_gain_I: 0.7
    ctrl_gain_D: 0.9
